### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by TakWolf** [iblh/hexo-theme-material#416]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

所有页面都会报这个错误：
![image](https://user-images.githubusercontent.com/6064962/27509914-836e0a6a-5939-11e7-914d-5f71dcbc45f6.png)
定位后在这里：
![image](https://user-images.githubusercontent.com/6064962/27509921-93e87376-5939-11e7-84aa-8b28ad491104.png)

不知道这里会影响啥，没发现页面哪里不对。

**Comment by neoFelhz** [comment]
Already fixed in `canary` branch.

**Comment by TakWolf** [comment]
已经切换到 canary 分支仍然有报错：（结点为：https://github.com/viosey/hexo-theme-material/commit/6e266a178cfdd4fbb8641f24091399d1c43f0435）

![image](https://user-images.githubusercontent.com/6064962/27513610-bd9086e0-599e-11e7-9aaf-a66435d6c1d5.png)

**Comment by TakWolf** [comment]
@neoFelhz 
yunsdk 是网易云跟帖的问题，先忽略这个。
报错的是上面的 addEventListener

![image](https://user-images.githubusercontent.com/6064962/27513888-d53327e2-59aa-11e7-88c3-32e4975d54fb.png)

**Comment by TakWolf** [comment]
定位之后是这里：

![image](https://user-images.githubusercontent.com/6064962/27513899-44bfc052-59ab-11e7-91d7-9d3dabbb8500.png)

没弄明白这个 js 是做什么用的

**Comment by neoFelhz** [comment]
@EYHN We may need to add `ls-javascript` for 163gentie.
